@extends('admin.layout')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><div class="eyebrow">YOUR COMMUNITY AT A GLANCE</div><h1>Good food. Great overview.</h1><p class="muted">A little clarity for everything happening around your carts.</p></div><a class="button" href="/admin/carts/create">+ Add food cart</a></div>
<div class="stats">@foreach($counts as $label=>$count)<article class="stat"><div>{{ $label }} <span>{{ ['Carts'=>'▱','Customers'=>'◎','Active follows'=>'♡','Pending review'=>'◷'][$label] }}</span></div><strong>{{ number_format($count) }}</strong><small>{{ $label==='Pending review'?'Waiting for your attention':'Across your community' }}</small></article>@endforeach</div>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><h2>Food carts</h2><p class="muted">The latest additions to your neighborhood.</p></div><a href="/admin/carts">View all ↗</a></div><div class="table-wrap"><table><thead><tr><th>Cart</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>@forelse($carts as $cart)<tr><td><strong>{{ $cart->name }}</strong><small>{{ $cart->cuisine ?: 'Street food' }}</small></td><td>{{ $cart->owner?->name }}</td><td><span class="badge {{ $cart->moderation_status }}">{{ $cart->moderation_status }}</span></td><td><a href="/admin/carts/{{ $cart->id }}/edit">Manage ↗</a></td></tr>@empty<tr><td colspan="4"><div class="empty"><span>▱</span><h3>Your first cart starts here.</h3><p>Add an owner account, then create their food cart.</p><a href="/admin/users/create">Create an owner →</a></div></td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Delivery health</h2><p class="muted">Keeping your community in the loop.</p></div><span class="icon-circle">↗</span></div><div class="delivery-count">{{ number_format($deliveries->get('sent',0)) }}<small>push messages delivered</small></div><div class="delivery-list">@foreach(['pending'=>'In queue','failed'=>'Needs attention','skipped'=>'Skipped by preferences'] as $key=>$label)<a href="/admin/deliveries"><span><i class="dot {{ $key }}"></i>{{ $label }}</span><strong>{{ $deliveries->get($key,0) }}</strong></a>@endforeach</div><div class="hint">Notifications are processed every 2 minutes when the scheduler is running.</div></section>
<section class="panel"><div class="panel-heading"><div><h2>Latest updates</h2><p class="muted">Fresh from the carts.</p></div><a href="/admin/updates">View all ↗</a></div>@forelse($updates as $update)<div class="activity"><span class="icon-circle">↗</span><div><strong>{{ $update->title }}</strong><p>{{ $update->cart?->name }} · {{ $update->created_at->diffForHumans() }}</p></div></div>@empty<div class="empty compact"><h3>All quiet for now.</h3><p>Published cart updates will appear here.</p></div>@endforelse</section>
<section class="callout"><div class="eyebrow">MAKE IT YOURS</div><h2>Your community.<br>Your settings.</h2><p>Manage push delivery and location freshness from one place.</p><a href="/admin/configuration">Open configuration <span>→</span></a></section></div>
@endsection
