@extends('admin.layout')
@section('title',ucwords(str_replace('-',' ',$resource)))
@section('content')
<div class="page-heading"><div><div class="eyebrow">COMMUNITY MANAGEMENT</div><h1>{{ ucwords(str_replace('-',' ',$resource)) }}</h1><p class="muted">{{ number_format($rows->total()) }} records in your workspace.</p></div>@if(in_array($resource,['users','carts','updates','schedules','follows','cart-locations','user-settings']))<a class="button" href="/admin/{{ $resource }}/create">+ Add record</a>@endif</div>
@if(in_array($resource,['users','carts']))<form class="search"><input name="search" value="{{ request('search') }}" placeholder="Search by name" aria-label="Search by name"><button class="button secondary">Search</button></form>@endif
<section class="panel table-wrap"><table><thead><tr><th>ID</th><th>Details</th><th>Last updated</th><th>Action</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>#{{ $row->id }}</td><td>
@if($resource==='photos')<img class="thumb" src="{{ $row->url }}" alt="Cart photo">@endif
@foreach(collect($row->getAttributes())->except(['id','password','remember_token','created_at','updated_at','token','token_hash','path','dedupe_key','fanout_at'])->take(8) as $key=>$value)<div class="detail"><span>{{ str_replace('_',' ',$key) }}</span> {{ \Illuminate\Support\Str::limit((string)$value,120) }}</div>@endforeach
</td><td class="nowrap">{{ $row->updated_at?->diffForHumans() }}</td><td><div class="actions">@if(in_array($resource,['users','carts','updates','schedules','follows','cart-locations','user-settings','reports']))<a href="/admin/{{ $resource }}/{{ $row->id }}/edit">Edit ↗</a>@endif
@if($resource==='deliveries' && $row->status==='failed')<form method="post" action="/admin/deliveries/{{ $row->id }}/retry">@csrf<button class="text-button">Retry</button></form>@endif
@if(in_array($resource,['updates','schedules','photos','follows','cart-locations','user-locations']))<form method="post" action="/admin/{{ $resource }}/{{ $row->id }}">@csrf @method('DELETE')<button class="text-button danger">Delete</button></form>@endif</div></td></tr>@empty<tr><td colspan="4"><div class="empty"><span>◫</span><h3>No records yet.</h3><p>New {{ str_replace('-',' ',$resource) }} will appear here.</p></div></td></tr>@endforelse</tbody></table></section><div class="pagination">@if($rows->previousPageUrl())<a href="{{ $rows->previousPageUrl() }}">← Previous</a>@endif <span>Page {{ $rows->currentPage() }} of {{ $rows->lastPage() }}</span> @if($rows->nextPageUrl())<a href="{{ $rows->nextPageUrl() }}">Next →</a>@endif</div>
@endsection
